prj/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

prj/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index_past/', views.index_article),
    path('dinner/', views.dinner),
    path('search/', views.search),
    path('throw/', views.throw),
    path('catch/', views.catch),
    path('hello/<str:name>/', views.greeting),
    path('index/', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # path('edit/<int:pk>/', views.edit, name = 'edit'),
    path('update/<int:pk>/', views.update, name='update'),
]

prj/prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('<int:user_pk>/password',views.change_password, name='change_password'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

prj/articles/models.py
from django.db import models

# Create your models here.
# 파이썬에서 클래스 인자는 상속이다.

'''
0. model 객체를 만든다(스케치본이라 한다.)
1. makemigrations 진행(개발자가 진행) -> 장고가 migration파일을 만든다.
2. migrate를 통해 db에 반영

'''
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # auto_now_add => 처음 생성될 때만 현재 시간 저장
    updated_at = models.DateTimeField(auto_now=True)
    # 저장될 때마다 현재 날짜 시간을 저장
    image = models.ImageField(blank=True)

prj/articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=10)
#     content = forms.CharField(widget=forms.Textarea())

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
         label='제목',
         widget=forms.TextInput(
              attrs={
                   'class': 'my-title',
                   'place-holder': '제목을 입력해주세요',
                   'maxLength':10,
              }
         )
    )
    class Meta:
         model = Article
         fields = '__all__'
        #  exclude = ('title',)

class ArticleForm_v2(forms.ModelForm):
     class Meta:
          model = Article
          fields = '__all__'

prj/articles/views.py
from django.shortcuts import render, redirect
import random
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index_article(request):
    context = {
        'name': 'soony',
    }
    return render(request, 'articles/index_past.html', context)

def dinner(request):
    foods = ['국밥', '고기', '라면', '감자']
    picked = random.choice(foods)
    context = {
        'foods': foods,
        'picked': picked,
    }
    return render(request, 'articles/dinner.html', context)

def search(request):
    return render(request, 'articles/search.html')

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message
    }
    return render(request, 'articles/catch.html', context)

def greeting(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/greeting.html', context)

def index(request):
    articles = Article.objects.all()
    articles_v2 = Article.objects.filter(content__contains='!')
    print(articles_v2)
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)
# def new(request):
#     form = ArticleForm()
#     context = {
#         'form':form
#     }
#     return render(request, 'articles/new.html', context)

# def create(request):
#     form = ArticleForm(request.POST)
#     if form.is_valid():
#         article = form.save()
#         return redirect('articles:detail', article.pk)
#     context = {
#         'form':form
#     }
#     return render(request, 'articles/new.html', context)

# def edit(request, pk):
#     article = Article.objects.get(pk = pk)
#     form = ArticleForm(instance=article)
#     context = {
#         'article':article,
#         'form': form,
#     }
#     return render(request, 'articles/edit.html', context)


# def update(request, pk):
#     article = Article.objects.get(pk = pk)
#     form = ArticleForm(request.POST, instance=article)

#     if form.is_valid():
#         form.save()
#         return redirect('articles:detail', article.pk)
#     context = {
#         'article': article,
#         'form': form,
#     }
#     return render(request, 'articles/edit.html', context)
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form':form,
    }
    return render(request, 'articles/create.html', context)

def update(request, pk):
    article = Article.objects.get(pk = pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES ,instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article':article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

prj/articles/templates/articles/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    네이게이션바
    {% block  content%}
    {% endblock  content%}
    
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

prj/articles/templates/articles/catch.html
{% extends "articles/base.html" %}

{% block content %}

    <h1>catch</h1>
    <p>요청 값: {{message}}</p>

{% endblock content %}

prj/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=f, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>create</h1>
    <form action="{% url 'articles:create' %}" method ="POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
</body>
</html>

prj/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>detail</h1>
    <p>{{article.pk}}번째 글</p>
    <hr>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    {% if article.image %}
        <img src="{{article.image.url}}" alt="img">
    {% endif %}
    <p>작성일 : {{article.created_at}}</p>
    <p>수정일 : {{article.updated_at}}</p>
    <hr>
    <a href="{% url "articles:index" %}">메인</a>
    <br>
    <a href="{% url 'articles:update' article.pk %}">수정하기</a>
</body>
</html>

prj/articles/templates/articles/dinner.html
{% extends "articles/base.html" %}

{% block content %}

    dinner
    <p>{{picked}} 메뉴는 {{picked|length}}글자입니다</p>
    <p>{{foods}}</p>
    <ul>
    {% for food in foods %}
        <li>
            {{food}}
        </li>
    {% endfor %}
    </ul>
    

    {% if  foods|length == 0%}
        <p>매뉴가 소진되었다</p>
    {% else %}
        <p>아직 메뉴 남아있다</p>
    {% endif %}
    
{% endblock content %}

prj/articles/templates/articles/greeting.html
{% extends "articles/base.html" %}

{% block content %}
    <h1>
        g
    </h1>
    <p>{{name}} 이 url 요청</p>
{% endblock content %}

prj/articles/templates/articles/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <img src="{% static "articles/mz3.jpg" %}" alt="sample">
    <img src="{% static "articles/mz4.jpg" %}" alt="엥">
    <img src="{% static %}" alt="">

    <img src="{% static "m3.jpg" %}" alt="adsa">
    <a href="{% url "accounts:login" %}">login</a>
    <form action="{% url "accounts:logout"%}" method="POST">
        {% csrf_token %}
        <input type="submit">
    </form>
    <a href="{% url "accounts:signup" %}">회원가입</a>
    <form action="{% url "accounts:delete"%}" method="POST">
        {% csrf_token %}
        <input type="button" value = "회원탈퇴">
    </form>
    {% for article in  articles%}
        <p>제목: {{article.title}}</p>
        <p>내용: {{article.content}}</p>
        <a href="{% url 'articles:detail' article.pk %}">게시글 보기</a>
        <hr>
    {% endfor %}
    <a href="{% url 'articles:create' %}">게시글 작성</a>
</body>
</html>

prj/articles/templates/articles/index_past.html
{% extends "articles/base.html" %}

{% block content %}
<h1>
    안녕하세요: {{name}}
</h1>
{% endblock content %}

prj/articles/templates/articles/search.html
{% extends "articles/base.html" %}

{% block content %}
    <h1>
        fake naver
    </h1>
    <form action="https://search.naver.com/search.naver" method = 'GET'>
        <input type="text" name='query'>
        <input type="submit">
    </form>
{% endblock content %}

prj/articles/templates/articles/throw.html
{% extends "articles/base.html" %}

{% block content %}

    <h1>throw</h1>
    <form action='/articles/catch' method = 'GET'>
        <input type="text" name = 'message'>
        <input type="submit">
    </form>

{% endblock content %}

prj/articles/templates/articles/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=f, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>update</h1>
    <form action="{% url 'articles:update' article.pk %}" method ="POST" enctype = 'multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value = "수정">
    </form>
</body>
</html>